apiVersion: v1
kind: Pod
metadata:
  name: configmap-pod
spec:
  containers:
    - name: test-container
      image: k8s.gcr.io/busybox
      command: [ "/bin/sh", "-c", "env; while true; do sleep 3600; done"]
      env:
        - name: SERVICE_JSON_FOR_MY_APP1
          valueFrom:
            configMapKeyRef:
              name: test-cm
              key: service.json
      envFrom:
        - configMapRef:
            name: from-env-file
