apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-class
provisioner: example.com/nfs
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
parameters:
  server: 192.168.1.100
  path: /nfs/data

